### PR TITLE
PKCE Implementation for issue #73

### PR DESCRIPTION
**Pull request by stamoun**
PKCE implementation as per [Spotify's docs](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow-with-proof-key-for-code-exchange-pkce).

Noteworthy items:

- I ran prettier on the whole project and added a prettier task in package.json (this could become a git commit hook at some point I guess)
- Prettier adds a lot of noise to the changes, all PKCE related changes occurred in:
  - auth.ts (used to be server.ts)
  - Lofi/index.tsx
  - Welcome/index.tsx
  - Cover/index.tsx
- Bumped version to 1.5.2 (in case you want to isolate pkce)

### CODE REVIEW

**Comment by stamoun** [comment]
In its current state, PKCE returns an 'INVALID_CLIENT: Invalid redirect URI' error when using the client id `69eca11b9ccd4bd3a7e01e6f9ddb5205`. I'm guessing that `http://localhost:41419` was removed from Lofi's Spotify dashboard. N.B. It works with port 8888.

**Review by dvx — COMMENTED** [review]
Ok, so I was *finally* able to look at this and test. The code quality is fantastic, so thanks for that!

Also, many thanks for running prettier on the whole project. There are a few aesthetic nits I have with it (for example, I like having ternary operators all on one line, and vector arrays split up neatly in 3-by-X matrices. But these are small issues that I will manually tackle.

PKCE works fine, but the flow is a bit strange. For example, in my case, I log in to Spotify via FB. So the window opens up and (1) I first log in to FB, (2) then log in to Spotify, and then I (3) have to *close* the window, and re-click the Lofi "Log in" button on the splash screen and then, I (4) can finally grant the permissions needed.

This is a bit confusing, and also a bit sketchy: why would you type in your FB credentials in a random app you downloaded? Is there any way PKCE can work with the native browser? I'd even be okay with keeping the current `auth.lofi.rocks` endpoint alive, just so we can avoid having people type in their credentials in the Lofi "pop-up."

Anyway, would love to hear your thoughts, and thanks again for the huge contribution!

**Comment by stamoun** [comment]
>  I like having ternary operators all on one line, and vector arrays split up neatly in 3-by-X matrices.

This is probably configurable in `.pretierrc.json` I just left everything by default (except for the `endOfLine: auto`). I'll take a look at it.

> Is there any way PKCE can work with the native browser?

The reason why I did a popup from within Lofi itself is simply because I like apps to be self-contained (I guess it comes from my desktop app dev days). I see no issues with using the default browser to manage the auth flow. I will try to use the default browser instead of that popup (like the previous behaviour); if it's fine I'll push the change so you can test it.

I don't log in through FB (I don't even have a FB account, yeah I'm one of those hehe), so I didn't notice anything weird sorry about that. The auth flow I encountered is just the popup, log in then accept Lofi's request. Any further log in attempts didn't require to log in again, just accept the auth requests (I manually delete the access/refresh tokens from the settings file to test this since we cannot revoke an app's access via the Spotify API).

**Comment by stamoun** [comment]
I remember why I used a built-in `BrowserWindow` instead of the default browser, it was because the `window.close()` response didn't close the tab with the default browser... I'll just add a message like 'You may now close this window'.

This is the warning I get when the app tries to close the window `Scripts may not close windows that were not opened by script.`; I'll check if there's a possible fix for that.

**Comment by stamoun** [comment]
Regarding prettier, ternary operators are normally on a single line unless they are over 80 columns wide. This is kind of small IMO; I usually run my IDEs with 120 column width wrapping (although, to be fair, 80 max is better on 1080p monitors). This can easily be set in `.prettierrc.json` with `printWidth: 120`. I'll wait to hear from you before making this change.

Regarding arrays, I don't think prettier has this level of flexiblity, sadly.

**Comment by dvx** [comment]
Re-tested, and it works perfectly fine! We can handle my prettier nitpicks in a separate PR, no sweat there! I'm gonna' go ahead and merge. This is an amazing contribution and thank you so much for your time and effort!

**Pull request merged**
