### PR TITLE
Featur: Control to toggle shuffle

### PR DESCRIPTION
**Pull request by WookieFPV**
added a button to toggle the spotify shuffle feature.

If you can make the ui prettier, feel free to do it.

### CODE REVIEW

**Comment by dvx** [comment]
Thanks for this @WookieFPV -- a feature a whole bunch of people have been asking for! Will test and merge this ASAP. It'll definitely make it in the next release.

**Comment by dvx** [comment]
Apologies for the super-late reply, but there are a few visual glitches with this PR (`cover` doesn't cover the entire player window), but I'll take a look at it and fix. Thanks for your work on the shuffle, feature though!

**Comment by WookieFPV** [comment]
hey thanks for looking into it.
I have no experience with electron and fairly low ts knowledge.
How can i debug the Code?

I tried turning debug mode in electron on but that resulted in a white window without any content.
Would be awesome if you could include a few lines on that in the readme.

I would love to contribute to this project.

**Comment by dvx** [comment]
Hey, no worries! Yeah, I need to add a bit more on how to contribute :) Also, there are no tests yet and that's also a nice to have. But basically, to debug, make sure to uncomment this line in `main.ts`:

```
  // Open the DevTools.
  // mainWindow.webContents.openDevTools({mode:"detach"});
```

It seems like it's just an issue with the CSS and could be fixed fairly easily. With that said, I'm not sure if we should have the shuffle button as part of the main three functions (back/pause/forward). Maybe we should put it on the side (above the visualization button maybe?) -- or maybe we should move the "help" button from the bottom-right to the top-left and have the shuffle toggle in the bottom-right.

Thoughts?

**Pull request closed without merging**
